# Generated by Django 5.2.7 on 2025-10-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adherent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "numero_securite_sociale",
                    models.CharField(
                        help_text="Numero de securite sociale unique",
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("date_adhesion", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Adherent",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_versement", models.DateField()),
                (
                    "adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotisations",
                        to="gestionapp.adherent",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_versement"],
            },
        ),
    ]
